package me.jdan.po;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsId
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private String newsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.keywords
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.authorId
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private String authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.releaseDate
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private Date releasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsIntro
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private String newsintro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsType
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private Integer newstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.privilege
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private Integer privilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsContent
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    private byte[] newscontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsId
     *
     * @return the value of news.newsId
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public String getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsId
     *
     * @param newsid the value for news.newsId
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setNewsid(String newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.keywords
     *
     * @return the value of news.keywords
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.keywords
     *
     * @param keywords the value for news.keywords
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.authorId
     *
     * @return the value of news.authorId
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public String getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.authorId
     *
     * @param authorid the value for news.authorId
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setAuthorid(String authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.releaseDate
     *
     * @return the value of news.releaseDate
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public Date getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.releaseDate
     *
     * @param releasedate the value for news.releaseDate
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsIntro
     *
     * @return the value of news.newsIntro
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public String getNewsintro() {
        return newsintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsIntro
     *
     * @param newsintro the value for news.newsIntro
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setNewsintro(String newsintro) {
        this.newsintro = newsintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsType
     *
     * @return the value of news.newsType
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public Integer getNewstype() {
        return newstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsType
     *
     * @param newstype the value for news.newsType
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setNewstype(Integer newstype) {
        this.newstype = newstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.privilege
     *
     * @return the value of news.privilege
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public Integer getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.privilege
     *
     * @param privilege the value for news.privilege
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setPrivilege(Integer privilege) {
        this.privilege = privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsContent
     *
     * @return the value of news.newsContent
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public byte[] getNewscontent() {
        return newscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsContent
     *
     * @param newscontent the value for news.newsContent
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    public void setNewscontent(byte[] newscontent) {
        this.newscontent = newscontent;
    }
}