package me.jdan.po;

public class Newscategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newscategory.typeId
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newscategory.fType
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    private Integer ftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newscategory.name
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newscategory.description
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newscategory.typeId
     *
     * @return the value of newscategory.typeId
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newscategory.typeId
     *
     * @param typeid the value for newscategory.typeId
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newscategory.fType
     *
     * @return the value of newscategory.fType
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public Integer getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newscategory.fType
     *
     * @param ftype the value for newscategory.fType
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public void setFtype(Integer ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newscategory.name
     *
     * @return the value of newscategory.name
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newscategory.name
     *
     * @param name the value for newscategory.name
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newscategory.description
     *
     * @return the value of newscategory.description
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newscategory.description
     *
     * @param description the value for newscategory.description
     *
     * @mbggenerated Mon Oct 31 20:34:54 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}