package me.jdan.dao;

import java.util.List;
import me.jdan.po.Newscategory;
import me.jdan.po.NewscategoryExample;
import org.apache.ibatis.annotations.Param;

public interface NewscategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int countByExample(NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int deleteByExample(NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int insert(Newscategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int insertSelective(Newscategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    List<Newscategory> selectByExample(NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    Newscategory selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Newscategory record, @Param("example") NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int updateByExample(@Param("record") Newscategory record, @Param("example") NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int updateByPrimaryKeySelective(Newscategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Thu Oct 27 21:04:46 CST 2016
     */
    int updateByPrimaryKey(Newscategory record);
}